ARG NODE_IMAGE=docker.m.daocloud.io/library/node:20-alpine
ARG NGINX_IMAGE=docker.m.daocloud.io/library/nginx:1.27-alpine

FROM ${NODE_IMAGE} AS build
WORKDIR /web
COPY apps/web/package.json apps/web/package-lock.json* ./
RUN npm install --registry=https://registry.npmmirror.com
COPY apps/web/ ./
RUN npm run build

FROM ${NGINX_IMAGE}
COPY --from=build /web/dist /usr/share/nginx/html
COPY deploy/web-nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
